// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swyhugeyamssgnufaueq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3eWh1Z2V5YW1zc2dudWZhdWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODI0OTksImV4cCI6MjA3MTQ1ODQ5OX0.OxJEBAr2hzcSMOxQShu23iNWS8SfM8Ul4aX33GhH5lI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});